'\" t
.\"     Title: \fBkmag\fR
.\"    Author: Lauri Watts <lauri@kde.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2010-10-06
.\"    Manual: KDE User's Manual
.\"    Source: K Desktop Environment
.\"  Language: English
.\"
.TH "\FBKMAG\FR" "1" "2010\-10\-06" "K Desktop Environment" "KDE User's Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kmag \- Screen magnifier
.SH "SYNOPSIS"
.HP \w'\fBkmag\fR\ 'u
\fBkmag\fR [KDE\ Generic\ Options] [Qt(TM)\ Generic\ Options]
.SH "DESCRIPTION"
.PP
\fBkmag\fR, also known as
KMagnifier
is a screen magnifier\&. You can use
KMagnifier
to magnify a part of the screen just as you would use a lens to magnify a newspaper fine\-print or a photograph\&. This application is useful for a variety of people: from researchers to artists to web\-designers to people with low vision\&.
.SH "SEE ALSO"
.PP
More detailed user documentation is available from
\m[blue]\fBhelp:/kmag\fR\m[]
(either enter this
URL
into
Konqueror, or run
\fB\fBkhelpcenter\fR\fR\fB \fR\fB\fIhelp:/kmag\fR\fR)\&.
.PP
There is also further information available at the
\m[blue]\fBKDE accessibility project home page\&.\fR\m[]\&\s-2\u[1]\d\s+2
.SH "AUTHORS"
.PP
KMagnifier
was written by
Olaf Schmidt<ojschmidt@kde\&.org>
and
Sarang Lakare<sarang@users\&.sf\&.net>
and
Michael Forster<forster@fmi\&.uni\-passau\&.de>
.SH "AUTHOR"
.PP
\fBLauri Watts\fR <\&lauri@kde\&.org\&>
.RS 4
Author.
.RE
.SH "NOTES"
.IP " 1." 4
KDE accessibility project home page.
.RS 4
\%http://accessibility.kde.org/
.RE
