# QAccessibilityClientConfig.cmake is generated by CMake from QAccessibilityClientConfig.cmake.in

# Thanks to the generated exported target, simply use qaccessibilityclient
# e.g. target_link_libraries(mytarget qaccessibilityclient)
include(/usr/local/lib/cmake/QAccessibilityClient/QAccessibilityClient.cmake)

set(QACCESSIBILITYCLIENT_VERSION_MAJOR 0)
set(QACCESSIBILITYCLIENT_VERSION_MINOR 1)
set(QACCESSIBILITYCLIENT_VERSION_PATCH 0)
set(QACCESSIBILITYCLIENT_VERSION ${QACCESSIBILITYCLIENT_VERSION_MAJOR}.${QACCESSIBILITYCLIENT_VERSION_MINOR}.${QACCESSIBILITYCLIENT_VERSION_PATCH})

set(QACCESSIBILITYCLIENT_INCLUDE_DIR         "/usr/local/include")
set(QACCESSIBILITYCLIENT_LIBRARY             qaccessibilityclient)

